// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: contructOrder.proto

package BuyerBot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetOrderInfo_GetOrder_FullMethodName = "/order.GetOrderInfo/GetOrder"
)

// GetOrderInfoClient is the client API for GetOrderInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetOrderInfoClient interface {
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
}

type getOrderInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewGetOrderInfoClient(cc grpc.ClientConnInterface) GetOrderInfoClient {
	return &getOrderInfoClient{cc}
}

func (c *getOrderInfoClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, GetOrderInfo_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetOrderInfoServer is the server API for GetOrderInfo service.
// All implementations must embed UnimplementedGetOrderInfoServer
// for forward compatibility.
type GetOrderInfoServer interface {
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	mustEmbedUnimplementedGetOrderInfoServer()
}

// UnimplementedGetOrderInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetOrderInfoServer struct{}

func (UnimplementedGetOrderInfoServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedGetOrderInfoServer) mustEmbedUnimplementedGetOrderInfoServer() {}
func (UnimplementedGetOrderInfoServer) testEmbeddedByValue()                      {}

// UnsafeGetOrderInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetOrderInfoServer will
// result in compilation errors.
type UnsafeGetOrderInfoServer interface {
	mustEmbedUnimplementedGetOrderInfoServer()
}

func RegisterGetOrderInfoServer(s grpc.ServiceRegistrar, srv GetOrderInfoServer) {
	// If the following call panics, it indicates UnimplementedGetOrderInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetOrderInfo_ServiceDesc, srv)
}

func _GetOrderInfo_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetOrderInfoServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetOrderInfo_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetOrderInfoServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetOrderInfo_ServiceDesc is the grpc.ServiceDesc for GetOrderInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetOrderInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.GetOrderInfo",
	HandlerType: (*GetOrderInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrder",
			Handler:    _GetOrderInfo_GetOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contructOrder.proto",
}
