// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: contructOrder.proto

package BuyerBot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdOfCustomer  string                 `protobuf:"bytes,2,opt,name=idOfCustomer,proto3" json:"idOfCustomer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_contructOrder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_contructOrder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_contructOrder_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetIdOfCustomer() string {
	if x != nil {
		return x.IdOfCustomer
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_contructOrder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contructOrder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_contructOrder_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderRequest) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_contructOrder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contructOrder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_contructOrder_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

var File_contructOrder_proto protoreflect.FileDescriptor

const file_contructOrder_proto_rawDesc = "" +
	"\n" +
	"\x13contructOrder.proto\x12\x05order\";\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\fidOfCustomer\x18\x02 \x01(\tR\fidOfCustomer\"5\n" +
	"\x0fGetOrderRequest\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order\"6\n" +
	"\x10GetOrderResponse\x12\"\n" +
	"\x05order\x18\x01 \x01(\v2\f.order.OrderR\x05order2K\n" +
	"\fGetOrderInfo\x12;\n" +
	"\bGetOrder\x12\x16.order.GetOrderRequest\x1a\x17.order.GetOrderResponseB(Z&github.com/voznikaetnepriyazn/BuyerBotb\x06proto3"

var (
	file_contructOrder_proto_rawDescOnce sync.Once
	file_contructOrder_proto_rawDescData []byte
)

func file_contructOrder_proto_rawDescGZIP() []byte {
	file_contructOrder_proto_rawDescOnce.Do(func() {
		file_contructOrder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contructOrder_proto_rawDesc), len(file_contructOrder_proto_rawDesc)))
	})
	return file_contructOrder_proto_rawDescData
}

var file_contructOrder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_contructOrder_proto_goTypes = []any{
	(*Order)(nil),            // 0: order.Order
	(*GetOrderRequest)(nil),  // 1: order.GetOrderRequest
	(*GetOrderResponse)(nil), // 2: order.GetOrderResponse
}
var file_contructOrder_proto_depIdxs = []int32{
	0, // 0: order.GetOrderRequest.order:type_name -> order.Order
	0, // 1: order.GetOrderResponse.order:type_name -> order.Order
	1, // 2: order.GetOrderInfo.GetOrder:input_type -> order.GetOrderRequest
	2, // 3: order.GetOrderInfo.GetOrder:output_type -> order.GetOrderResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_contructOrder_proto_init() }
func file_contructOrder_proto_init() {
	if File_contructOrder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contructOrder_proto_rawDesc), len(file_contructOrder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contructOrder_proto_goTypes,
		DependencyIndexes: file_contructOrder_proto_depIdxs,
		MessageInfos:      file_contructOrder_proto_msgTypes,
	}.Build()
	File_contructOrder_proto = out.File
	file_contructOrder_proto_goTypes = nil
	file_contructOrder_proto_depIdxs = nil
}
